apiVersion: skaffold/v3alpha1
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: sidiik/department-service-app
      context: departments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: sidiik/shift-service-app
      context: shifts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: sidiik/users-service-app
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
