apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  labels:
    name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: my-app.org
      http:
        paths:
          - pathType: Prefix
            path: '/api/users'
            backend:
              service:
                name: users-service-app
                port:
                  number: 4000
          - pathType: Prefix
            path: '/api/departments/'
            backend:
              service:
                name: department-service
                port:
                  number: 4001
          - pathType: Prefix
            path: '/client'
            backend:
              service:
                name: client-service-app
                port:
                  number: 3000

          - pathType: Prefix
            path: '/api/shifts'
            backend:
              service:
                name: shift-service-app
                port:
                  number: 4002
